const quotes = [
 "The happiness of your life depends on the quality of your thoughts.",
 "Take a good look deep within yourself. There is a source of strength that will help you to rise again and again. That's only if you really look for it.",
 "Human nature is the same. We are all subject to the same impulses and desires.",
 "Fame, no matter how great, will always slip into the sands of history, and the pursuit of it only demonstrates the vanity we have.",
 "The only pain you suffer is that which you inflict on yourself; because you blame yourself or others. The real pain exists only in your mind.",
 "Whenever you wake up in the morning, think of the privilege of being alive, of being able to think, to love, and to enjoy.",
 "Be aware of the humility of others.",
 "What you hear is an opinion, not the truth. What you see is perspective, not reality.",
 "Love and rely on the little craft you've learned. Spend the rest of your life as a man who has entrusted to the gods, with all his soul, all his possessions, and who makes himself neither tyrant nor slave of another man.",
 "The art of living is more akin to the craft of wrestling than to the art of dancing, in that it requires that you face everything that comes your way, even unforeseen events, with vigor and well prepared.",
 "Remember, in any circumstance that would drive you to suffer, to avail yourself of this advice: it is not misfortune, but happiness to bear it nobly.",
 "Do not let the future spoil your peace of mind. If need be, you will face it with the same weapons of reason with which you fight today against the present.",
 "The shortness of time is common to all things, but you run from them all or pursue them as if they were eternal.",
 "All that happens to each, serves the whole.",
 "Look deep within your being! There lies a wellspring of goodness that will not cease to flow as long as you do not cease to seek.",
 "It is ridiculous not to run away from your own wickedness - which you can - and to run away from the wickedness of others, which you cannot!",
 "Do everything in life as if it were the last thing you do.",
 "Peace of mind comes when you stop worrying about what others say.",
 "The closer a man is to a calm mind, the closer he will be to finding his strength.",
 "No disgust, no discouragement, if you have just failed, start again. Many times, not only those who do, but also those who fail to do something, fail.",
 "Most of the things we say and do are unnecessary. The person who will eliminate them from his life will be more peaceful and serene.",
 "The consequences of anger are more painful than its causes.",
 "A man's worth is only as great as his ambitions.",
 "Loss is nothing but change, and change is Nature's pleasure.",
 "Recognize that others can only hurt you if you let them.",
 "You have power over your mind, not over events. Realize this and you will find power.",
 "Nowhere can man find such a peaceful and quiet refuge as in the privacy of his soul.",
 "Do not despise death, accept it willingly, for it is part of what is predetermined.",
 "All that exists is an opinion, and your opinion depends on you",
 "You want revenge on your enemy - always do him good.",
 "It is a man's privilege to love the one who makes him suffer.",
 "Teach yourself as much as you can to listen to anyone and to put yourself, as much as you can, in the soul of the one with whom you are talking.",
 "Receive without pride and give without regret.",
 "The first rule is to keep an unperturbed spirit. The second is to look things in the face and recognize them for exactly what they are.",
 "Accept the beauty of life. Follow the stars and imagine yourself running with them.",
 "Accept all the things that fate chains you with and love the people fate brings, but do so wholeheartedly.",
 "Everything that comes to you woven as the pattern of your destiny, accept it. This is what you really need.",
 "Death smiles on us all, but all man can do is smile back.",
 "A man's true pleasure is to do the thing he was made to do.",
]

function newQuote() {
    let randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}